name: "valiDTr"
description: "Verify signed commits against a time-aware developer/key allowlist"

inputs:
  config:
    required: true
    default: ".validtr/config.yml"
  pubkeys:
    required: true
    default: ".validtr/pubkeys/*.asc"
  policy:
    required: false
    default: "historical"
  email_mode:
    required: false
    default: "committer"

runs:
  using: "composite"
  steps:
    - name: Install required tools
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git gnupg jq gcc libc6-dev ca-certificates

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"
        cache: true
        cache-dependency-path: |
          ${{ github.action_path }}/../../../go.mod
          ${{ github.action_path }}/../../../go.sum

    - name: Build valiDTr (from action repo)
      shell: bash
      run: |
        set -euo pipefail

        REPO_ROOT="$(cd "$GITHUB_ACTION_PATH/../../.." && pwd)"

        # Don't inherit consumer repo go.work.
        export GOWORK=off

        # github.com/mattn/go-sqlite3 needs CGO.
        export CGO_ENABLED=1

        pushd "$REPO_ROOT" >/dev/null
        go build -o "$RUNNER_TEMP/valiDTr" .
        popd >/dev/null

        echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

    - name: Setup GnuPG home
      shell: bash
      run: |
        set -euo pipefail
        echo "GNUPGHOME=$RUNNER_TEMP/gnupg" >> "$GITHUB_ENV"
        mkdir -p "$RUNNER_TEMP/gnupg"
        chmod 700 "$RUNNER_TEMP/gnupg"

    - name: Import allowed public keys
      shell: bash
      run: |
        set -euo pipefail
        shopt -s nullglob
        for f in ${{ inputs.pubkeys }}; do
          gpg --batch --import "$f" >/dev/null
        done

    - name: Sync allowlist (preserves history)
      shell: bash
      run: |
        set -euo pipefail
        export VALIDTR_DB="$RUNNER_TEMP/validtr.db"
        valiDTr sync --config "${{ inputs.config }}" --mode=reconcile

    - name: Verify range
      shell: bash
      run: |
        set -euo pipefail
        export VALIDTR_DB="$RUNNER_TEMP/validtr.db"

        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          BASE="$(jq -r .pull_request.base.sha "$GITHUB_EVENT_PATH")"
          TO="$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")"
          FROM="$(git merge-base "$BASE" "$TO")"
        else
          FROM="$(jq -r .before "$GITHUB_EVENT_PATH")"
          TO="${GITHUB_SHA}"
        fi

        echo "Range: $FROM..$TO"
        valiDTr --policy="${{ inputs.policy }}" --email-mode="${{ inputs.email_mode }}" verify-range "$FROM" "$TO"
