name: "valiDTr"
description: "Verify signed commits against a time-aware developer/key allowlist"
inputs:
  config:
    description: "Path to .validtr/config.yml"
    required: true
    default: ".validtr/config.yml"
  pubkeys:
    description: "Glob for ASCII-armored pubkeys to import"
    required: true
    default: ".validtr/pubkeys/*.asc"
  policy:
    description: "current|historical"
    required: false
    default: "current"
  email_mode:
    description: "committer|author"
    required: false
    default: "committer"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Install valiDTr
      shell: bash
      run: |
        set -euo pipefail
        go install github.com/esuarken/valiDTr@latest

    - name: Import allowed public keys
      shell: bash
      run: |
        set -euo pipefail
        export GNUPGHOME="$RUNNER_TEMP/gnupg"
        mkdir -p "$GNUPGHOME"
        chmod 700 "$GNUPGHOME"
        shopt -s nullglob
        for f in ${{ inputs.pubkeys }}; do
          gpg --batch --import "$f"
        done

    - name: Sync allowlist from YAML
      shell: bash
      run: |
        set -euo pipefail
        export VALIDTR_DB="$RUNNER_TEMP/validtr.db"
        valiDTr sync --config "${{ inputs.config }}" --reset

    - name: Verify range (auto-detect event)
      shell: bash
      run: |
        set -euo pipefail
        export VALIDTR_DB="$RUNNER_TEMP/validtr.db"

        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          git fetch --no-tags --prune --depth=0 origin \
            "${GITHUB_BASE_REF}:${GITHUB_BASE_REF}" \
            "${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}"

          git checkout --force "${GITHUB_HEAD_REF}"
          FROM="$(git merge-base "${GITHUB_BASE_REF}" HEAD)"
          TO="$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")"
        else
          FROM="$(jq -r .before "$GITHUB_EVENT_PATH")"
          TO="${GITHUB_SHA}"
        fi

        echo "Range: $FROM..$TO"
        valiDTr --policy="${{ inputs.policy }}" --email-mode="${{ inputs.email_mode }}" verify-range "$FROM" "$TO"
