/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#pragma GCC diagnostic ignored "-Wunaligned-access"
extern void crosscall2(void (*fn)(void *), void *, int, size_t);
extern size_t _cgo_wait_runtime_init_done(void);
extern void _cgo_release_context(size_t);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_0470baca2faa_callbackTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void callbackTrampoline(sqlite3_context* ctx, GoInt argc, sqlite3_value** argv)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		sqlite3_context* p0;
		GoInt p1;
		sqlite3_value** p2;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = ctx;
	_cgo_a.p1 = argc;
	_cgo_a.p2 = argv;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_callbackTrampoline, &_cgo_a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_0470baca2faa_stepTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void stepTrampoline(sqlite3_context* ctx, int argc, sqlite3_value** argv)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		sqlite3_context* p0;
		int p1;
		char __pad0[4];
		sqlite3_value** p2;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = ctx;
	_cgo_a.p1 = argc;
	_cgo_a.p2 = argv;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_stepTrampoline, &_cgo_a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_0470baca2faa_doneTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void doneTrampoline(sqlite3_context* ctx)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		sqlite3_context* p0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = ctx;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_doneTrampoline, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_0470baca2faa_compareTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) int compareTrampoline(void* handlePtr, int la, char* a, int lb, char* b)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		int p1;
		char __pad0[4];
		char* p2;
		int p3;
		char __pad1[4];
		char* p4;
		int r0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handlePtr;
	_cgo_a.p1 = la;
	_cgo_a.p2 = a;
	_cgo_a.p3 = lb;
	_cgo_a.p4 = b;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_compareTrampoline, &_cgo_a, 44, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_0470baca2faa_commitHookTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) GoInt commitHookTrampoline(void* handle)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		GoInt r0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_commitHookTrampoline, &_cgo_a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_0470baca2faa_rollbackHookTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void rollbackHookTrampoline(void* handle)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_rollbackHookTrampoline, &_cgo_a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_0470baca2faa_updateHookTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void updateHookTrampoline(void* handle, GoInt op, char* db, char* table, GoInt64 rowid)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		GoInt p1;
		char* p2;
		char* p3;
		GoInt64 p4;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_a.p1 = op;
	_cgo_a.p2 = db;
	_cgo_a.p3 = table;
	_cgo_a.p4 = rowid;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_updateHookTrampoline, &_cgo_a, 40, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_0470baca2faa_authorizerTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) GoInt authorizerTrampoline(void* handle, GoInt op, char* arg1, char* arg2, char* arg3)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		GoInt p1;
		char* p2;
		char* p3;
		char* p4;
		GoInt r0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_a.p1 = op;
	_cgo_a.p2 = arg1;
	_cgo_a.p3 = arg2;
	_cgo_a.p4 = arg3;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_authorizerTrampoline, &_cgo_a, 48, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
extern void _cgoexp_0470baca2faa_preUpdateHookTrampoline(void *);

CGO_NO_SANITIZE_THREAD
__declspec(dllexport) void preUpdateHookTrampoline(void* handle, GoUintptr dbHandle, GoInt op, char* db, char* table, GoInt64 oldrowid, GoInt64 newrowid)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		GoUintptr p1;
		GoInt p2;
		char* p3;
		char* p4;
		GoInt64 p5;
		GoInt64 p6;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = handle;
	_cgo_a.p1 = dbHandle;
	_cgo_a.p2 = op;
	_cgo_a.p3 = db;
	_cgo_a.p4 = table;
	_cgo_a.p5 = oldrowid;
	_cgo_a.p6 = newrowid;
	_cgo_tsan_release();
	crosscall2(_cgoexp_0470baca2faa_preUpdateHookTrampoline, &_cgo_a, 56, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}

CGO_NO_SANITIZE_THREAD
void _cgo_0470baca2faa_Cfunc__Cmalloc(void *v) {
	struct {
		unsigned long long p0;
		void *r1;
	} __attribute__((__packed__, __gcc_struct__)) *a = v;
	void *ret;
	_cgo_tsan_acquire();
	ret = malloc(a->p0);
	if (ret == 0 && a->p0 == 0) {
		ret = malloc(1);
	}
	a->r1 = ret;
	_cgo_tsan_release();
}
